force-app/main/default/objects/Prompt__c/Prompt__c.object-meta.xml
<CustomObject>
    <description>A Prompt used in a ML orchestration</description>
    <label>Prompt</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prompt__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <description>The text of the Prompt for Completions, the Input field for Edits, and the User message for Chats</description>
    <inlineHelpText>The text of the Prompt for Completions, the Input field for Edits, and the User message for Chats</inlineHelpText>
    <label>Prompt</label>
    <length>8196</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PromptAnswer__c/PromptAnswer__c.object-meta.xml
<CustomObject>
    <description>A Response or Answer to a Prompt</description>
    <label>Prompt Answer</label>
    <nameField>
        <label>Prompt Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromptAnswer__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Prompt from which this Response was generated</description>
    <inlineHelpText>The Prompt from which this Response was generated</inlineHelpText>
    <label>Prompt</label>
    <referenceTo>Prompt__c</referenceTo>
    <relationshipName>PromptResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PromptStatsController.cls
/**
 * @description This class serves as a controller for retrieving statistics about Prompt records and PromptAnswer records.
 * It's generally used to display these statistics on a Visualforce page or a Lightning Component.
 *
 * The two main properties, `totalPrompts` and `totalAnswers`, represent the total count of records in `Prompt__c` and `PromptAnswer__c` respectively.
 */

public with sharing class PromptStatsController {
	public Integer totalPrompts {
		get; set;
	}
	public Integer totalAnswers {
		get; set;
	}

	public PromptStatsController() {
		totalPrompts = [SELECT count() FROM Prompt__c];
		totalAnswers = [SELECT count() FROM PromptAnswer__c];
	}

}